services:
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    restart: always
    environment:
      CONTAINERS: 1
      IMAGES: 1
      BUILD: 1
      NETWORKS: 1
      SYSTEM: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - aphelion-net
  app:
    container_name: aphelion
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=tcp://docker-proxy:2375
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    volumes:
      - .:/app:ro
      - .env:/app/.env:ro
      - node_modules:/app/node_modules
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "1000:1000"
    networks:
      - aphelion-net
networks:
  aphelion-net:
    driver: bridge
volumes:
  node_modules:
